version: "3.8"

services:
  # db:
  #   image: "mcr.microsoft.com/mssql/server:2022-latest"
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     MSSQL_SA_PASSWORD: saPassword123
  #   ports:
  #     - 1433:1433
  #   container_name: assetsapi-db
  #   volumes:
  #     - db-data:/var/lib/mssql

  assetsapi:
    build:
      context: .
      # dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
    # command:
    #   [
    #     "dotnet",
    #     "watch",
    #     "run",
    #     -v,
    #     "--project",
    #     "AssetManagement/AssetManagement.csproj",
    #     "--urls",
    #     "https://*:443;http://*:8080"
    #   ]
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https\:/root/.aspnet/https/
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
volumes:
  db-data:
